imports:
    - php

tools:
    php_mess_detector: true
    php_code_coverage: true
    php_pdepend: true
    external_code_coverage:
        timeout: 600
        runs: 3
    php_code_sniffer:
        config:
            standard: PSR4
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

checks:
    php: true

before_commands:
    - 'composer install --dev'

filter:
    excluded_paths: [ vendor/*, tests/* ]