imports:
    - php

tools:
    php_mess_detector: true
    php_code_coverage: false
    php_pdepend: true
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR4
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

checks:
    php: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true

before_commands:
    - composer install --dev

filter:
    excluded_paths: [ vendor/*, tests/* ]