imports:
    - php

tools:
    php_mess_detector: true
    php_code_coverage: false
    php_pdepend: true
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR4
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

checks:
    php:
        property_assignments: true
        return_doc_comments: true
        parameter_doc_comments: true
        verify_property_names: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        return_doc_comment_if_not_inferrable: true
        avoid_todo_comments: true
        encourage_single_quotes: true
        no_long_variable_names:
            maximum: '25'

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true

before_commands:
    - composer install --dev

filter:
    excluded_paths: [ vendor/*, tests/* ]