language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'
#    - 'nightly' # Disabled because xdebug_get_headers function missing

install:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

allow_failures:
    - php: nightly
