language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - 'nightly' # Disabled because xdebug_get_headers function missing

install:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script:
    - CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")
    - IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]})
    - vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no "${EXTRA_ARGS[@]}"
    - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
    allow_failures:
        - php: nightly