language: php
php:
  - '5.6'
  - '7.0'
  - 'hhvm'
  - 'nightly'
install:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover --verbose
allow_failures:
  - php: nightly
  - php: hhvm